CREATE TABLE IF NOT EXISTS metrics_aspects_starter_time_limit_exceed_log
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    method_signature TEXT                                    NOT NULL,
    measured_time_ms DOUBLE PRECISION                        NOT NULL,
    logged_at        TIMESTAMP with time zone                NOT NULL,
    CONSTRAINT pk_metrics_aspects_starter_time_limit_exceed_log PRIMARY KEY (id)
);
--
CREATE TABLE IF NOT EXISTS metrics_aspects_starter_data_source_error_log
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stacktrace       TEXT,
    message          TEXT,
    method_signature TEXT,
    CONSTRAINT pk_metrics_aspects_starter_data_source_error_log PRIMARY KEY (id)
);